#ifndef _ERRORCODES_H
#define _ERRORCODES_H

#define _ERRNO_NULL_POINTER_CMAN    0xFFFE
#define _ERRNO_NULL_POINTER_CCOM    0xFFFD
#define _ERRNO_NULL_POINTER_CMOT    0xFFFC
#define _ERRNO_NULL_POINTER_CSEN    0xFFFB
#define _ERRNO_NULL_POINTER_CTST    0xFF0F

#endif